# containers need to be launched in 'streampusher_default' network
#
# docker-compose -p streampusher icecast up -d
version: '3'
services:
  icecast:
    image: "mcfiredrill/icecast:latest"
    ports:
     - "8000:8000"
    restart: "always"
    volumes:
      - /usr/local/share/icecast/logs:/var/www/stream_pusher/shared/log/icecast
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: "always"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./redis-data:/data
  rails:
    image: "streampusher/streampusher:latest"
    user: rails
    working_dir: /home/rails/app
    command: ./docker_wrapper.sh bundle exec rails server -b '0.0.0.0'
    env_file: .env
    environment: &shared_env
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - .:/home/rails/app
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
  sidekiq:
    image: "streampusher/streampusher:latest"
    user: root
    working_dir: /home/rails/app
    command: ./docker_wrapper.sh bundle exec sidekiq
    env_file: .env
    environment:
      <<: *shared_env
    depends_on:
      - redis
    volumes:
      - .:/home/rails/app
      -  /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
