#!/bin/bash

docker-compose -f docker-compose-dev.yml  run rails ./docker_wrapper.sh bundle install --path vendor/bundle
docker-compose -f docker-compose-dev.yml  run rails ./docker_wrapper.sh bundle exec rake db:create
docker-compose -f docker-compose-dev.yml  run rails ./docker_wrapper.sh bundle exec rake db:migrate
