#!/bin/bash

if [ ! -f config/database.yml ]; then
  cp config/database.example.yml config/database.yml
fi
docker-compose -f docker-compose-dev.yml  run rails ./docker_wrapper.sh bundle install --path vendor/bundle
docker-compose -f docker-compose-dev.yml  run rails ./docker_wrapper.sh bundle exec rake db:create
docker-compose -f docker-compose-dev.yml  run rails ./docker_wrapper.sh bundle exec rake db:migrate
