#!/bin/bash
# https://www.destroyallsoftware.com/screencasts/catalog/fast-tests-with-and-without-rails

set -e

if [ $# -gt 0 ]; then # we have args
    filename=$1
else # we have no args
    filename='spec'
fi

if docker ps &>/dev/null; then
  # command="docker-compose -p streampusher -f docker-compose-dev.yml run rails ./docker_wrapper.sh bundle exec rspec"
  command="docker exec -it streampusher-rails-1 rbenv exec bundle exec rspec"
else
  command="bundle exec rspec"
fi

RAILS_ENV=test $command $filename
